### ISSUE TITLE
Backpack and Skillpoints

### ISSUE THREAD

**Issue by Moinsen81** [dsasmblr/cheat-engine#2]
Hi. great job again!
The script for the skillpoints does not work for me.
and it would be unbelievably nice if you could bring the backpack script to life again

**Comment by dsasmblr** [comment]
Sorry, I don't have the time to maintain old scripts like this. The backpack issue was much more of a problem due to how it's tied to the user profile, so you'll have to wait until Rick finishes his savegame editor and then use that. As for the skill points, I demonstrate in videos how to find those yourself, so give that a shot sometime if you're feeling adventurous. =)
