### ISSUE TITLE
inf health broke after recent patch

### ISSUE THREAD

**Issue by cgsweb** [dsasmblr/cheat-engine#4]
inf ammo continues to work but health appears to be broken after recent patch - was working prior to 

btw thank you for taking the time and creating this table!

**Comment by Crysis1007** [comment]
The Outer Worlds

Just downloaded the current CT for the current version of the game and the Inf Heath and OHK cheat is in fact broken. It seems to be giving myself and the enemies Inf Health and negating all damage I do. I don't think OHK is working correctly either because I am not able to damage any enemies.

**Comment by dsasmblr** [comment]
Sorry, I no longer have the time to maintain old scripts like this. I've demonstrated in videos how to find these values yourself to update the script, so give that a shot, or see if others will help you in the video comments.
